version: '3.8'

services:
  api:
    build: .
    working_dir: /app
    container_name: api
    image: ghcr.io/davide-almeida/abiscoitado:latest
    ports:
      - 3000:3000
    command: bash -c "bundle install && ruby server.rb -o 0.0.0.0 -p 3000"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: always
    environment:
      TZ: America/Sao_Paulo
    env_file:
      - .env
    volumes:
      - ./config/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "3001:3001"

networks:
  default:
    driver: bridge
    name: abiscoitado-network

volumes:
  database:
  rubygems:
