apiVersion: v1
kind: ConfigMap
metadata:
  name: abiscoitado-nginx-config
data:
  default.conf: |
    server {
        listen 3001;
        server_name localhost;

        location / {
            proxy_pass http://abiscoitado-api:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
