apiVersion: v1
kind: Service
metadata:
  name: abiscoitado-nginx-service
spec:
  selector:
    app: abiscoitado-nginx
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3001
  # type: LoadBalancer
